theme: minima
title: Naked Mormonism Show Notes
description: Skepticize Everything
twitter_username: NakedMormonism
facebook_username: Naked-Mormonism-370003839816311
timezone: America/Los_Angeles
permalink: /:year/:month/:day/:title/
disqus:
    shortname: namoscripts

author: Bryce Blankenagel
email: NakedMormonism@gmail.com

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at

exclude:
  - README.md
  - proc.py
  - shn 
  - Gemfile 
  - Gemfile.lock
  - namo_episodes.tsv

markdown: CommonMarkGhPages
