theme: minima
title: Naked Mormonism Show Notes
description: Skepticize Everything
twitter_username: NakedMormonism
facebook_username: Naked-Mormonism-370003839816311

author: Bryce Blankenagel
email: NakedMormonism@gmail.com

plugins:
  - jekyll-sitemap

exclude:
  - README.md
  - proc.py
  - shn 
  - Gemfile 
  - Gemfile.lock
  - namo_episodes.tsv
